import React, { useState, useEffect, useMemo } from 'react';
import {
  Sparkles,
  Camera,
  CheckCircle2,
  AlertTriangle,
  ShieldCheck,
  ArrowRight,
  ArrowLeft,
  Info,
  RefreshCw,
  Loader2,
  Plus,
  Bot,
  X,
  Send,
  History,
  Coins,
  Check,
  ExternalLink,
  Tag,
  DollarSign,
  PenLine,
  FileEdit,
  ChevronDown,
  ChevronUp,
  HelpCircle,
  MessageSquare
} from 'lucide-react';
import {
  ItemCategory,
  ConditionGrade,
  Listing,
  Language,
  CategoryBackend,
  ItemBackend
} from '../types';
import { translations, formatVND } from '../utils/translations';
import { numberToVietnameseWords, formatVndInput } from '../utils/numberToWords';
import {
  mediaService,
  postService,
  categoryService,
  itemService,
  aiChatService,
  sellerCreditService,
  CreditBalanceResponseDto,
  ListingDraftResponse,
  AiPriceEstimationResponse,
  PostSubmitResponse
} from '../services';
import { parseQuestionItem, splitCompoundQuestion } from '../utils/questionParser';



// Deleted getCategoryQuestionGuide and static templates. Templates are now solely fetched from the Backend DB.

interface CreateListingViewProps {
  onListingCreated: (newListing: Listing) => void;
  lang: Language;
  onCancel: () => void;
}

export const CreateListingView: React.FC<CreateListingViewProps> = ({
  onListingCreated,
  lang,
  onCancel
}) => {
  const t = translations[lang];

  // 5 Linear Steps matching Main Flow 1 Guide
  // Step 1: Chọn Category, Item & Tải 3-6 ảnh
  // Step 2: Mô tả AI & Chỉnh sửa / Chat
  // Step 3: Lưu Draft & Xác nhận mô tả
  // Step 4: Định giá AI (1 credit VALUATION) & Chọn giá bán
  // Step 5: Xem lại & Gửi đăng (1 credit LISTING khi ACTIVE)
  const [currentStep, setCurrentStep] = useState<1 | 2 | 3 | 4 | 5>(1);

  // Credit Balance State
  const [credits, setCredits] = useState<CreditBalanceResponseDto | null>(null);
  const [isLoadingCredits, setIsLoadingCredits] = useState(false);
  const [isPurchasingCredits, setIsPurchasingCredits] = useState(false);

  // Category & Item from Backend
  const [backendCategories, setBackendCategories] = useState<CategoryBackend[]>([]);
  const [backendItems, setBackendItems] = useState<ItemBackend[]>([]);
  const [selectedCategoryId, setSelectedCategoryId] = useState<string>('');
  const [selectedItemId, setSelectedItemId] = useState<string>('');
  const [isLoadingCategories, setIsLoadingCategories] = useState(false);
  const [isLoadingItems, setIsLoadingItems] = useState(false);

  // Basic Form State
  const [title, setTitle] = useState('');
  const [brand, setBrand] = useState('');
  const [model, setModel] = useState('');
  const [purchaseYear, setPurchaseYear] = useState<number>(new Date().getFullYear());
  const [originalPriceVnd, setOriginalPriceVnd] = useState<number | ''>('');
  const [itemCondition, setItemCondition] = useState<string>('USED_GOOD');
  const [description, setDescription] = useState('');
  const [finalPriceVnd, setFinalPriceVnd] = useState<number>(0);

  // Images state: Raw files for FormData & previews
  const [photoFiles, setPhotoFiles] = useState<File[]>([]);
  const [photoPreviews, setPhotoPreviews] = useState<string[]>([]);
  const [isUploadingPhoto, setIsUploadingPhoto] = useState(false);

  // Post & AI Session IDs from Backend
  const [postId, setPostId] = useState<string | null>(null);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [aiInitialMessage, setAiInitialMessage] = useState<string>('');
  const [draftPost, setDraftPost] = useState<ListingDraftResponse | null>(null);

  // Mode: 'ai' | 'manual'
  const [initMode, setInitMode] = useState<'ai' | 'manual' | null>(null);
  const [postMode, setPostMode] = useState<'ai' | 'manual'>('ai');
  const [showAiChatDrawer, setShowAiChatDrawer] = useState<boolean>(true);
  const [showQuestionsList, setShowQuestionsList] = useState<boolean>(true);

  // Derived category & item question guide
  const currentCategory = backendCategories.find(c => c.id === selectedCategoryId);
  const currentItem = backendItems.find(i => i.id === selectedItemId);

  // Removed static currentQuestionGuide

  // Warning from AI Vision (Llava) if uploaded image is detected as catalog / stock photo
  const isCatalogPhotoWarning = useMemo(() => {
    if (!aiInitialMessage) return false;
    const lower = aiInitialMessage.toLowerCase();
    return (
      lower.includes('ảnh quảng cáo') ||
      lower.includes('ảnh catalog') ||
      lower.includes('không phải ảnh chụp thực tế') ||
      lower.includes('không có cơ sở để đánh giá ngoại hình')
    );
  }, [aiInitialMessage]);

  // Dynamic question parser: Extracts questions generated by Backend AI from aiInitialMessage
  const parsedAiQuestions = useMemo(() => {
    if (!aiInitialMessage) return [];
    const lines = aiInitialMessage.split('\n');
    const questions: string[] = [];
    for (const line of lines) {
      const trimmed = line.trim();
      // Match "1. ...", "1) ...", "- 1. ...", "* 1. ..."
      const numMatch = trimmed.match(/^[-*•]?\s*(\d+)[\.\)]\s*(.+)$/);
      if (numMatch && numMatch[2]) {
        questions.push(numMatch[2].trim());
        continue;
      }
      // Match bullet with bold question: "- **Câu hỏi:** ..." or "* **Câu hỏi:** ..."
      const bulletBoldMatch = trimmed.match(/^[-*•]\s*(\*\*.*?\*\*.*)$/);
      if (bulletBoldMatch && bulletBoldMatch[1]) {
        questions.push(bulletBoldMatch[1].trim());
        continue;
      }
      // Match simple bullets with a question mark
      const bulletMatch = trimmed.match(/^[-*•]\s*(.+)$/);
      if (bulletMatch && bulletMatch[1] && bulletMatch[1].includes('?')) {
        questions.push(bulletMatch[1].trim());
        continue;
      }
      // Match any line ending with ?
      if (trimmed.endsWith('?')) {
        questions.push(trimmed);
      }
    }

    // If we couldn't parse structured lines but the message contains a question mark,
    // we can split the text by '?' as a fallback.
    if (questions.length === 0 && aiInitialMessage.includes('?')) {
      const parts = aiInitialMessage.split('?').map(p => p.trim()).filter(p => p.length > 10);
      parts.forEach(p => questions.push(p + '?'));
    }

    // Fallback for paragraph with a list: "Vui lòng cung cấp thêm: Hãng, Model, Tình trạng (mới/cũ)..."
    if (questions.length === 0) {
      const lastColonIdx = aiInitialMessage.lastIndexOf(':');
      if (lastColonIdx !== -1) {
        const listStr = aiInitialMessage.substring(lastColonIdx + 1).replace(/\.$/, '').trim();
        // Split by comma or semicolon, but NOT if it is inside parentheses ()
        const parts = listStr.split(/[,;]\s*(?![^()]*\))/).map(p => p.trim().replace(/^(và|hoặc)\s+/i, '')).filter(p => p.length > 2);
        if (parts.length > 1) {
          parts.forEach(p => questions.push(p + '?'));
        }
      }
    }

    // Final fallback: if nothing worked, just treat the whole message as one question so the form doesn't disappear
    if (questions.length === 0 && aiInitialMessage.trim().length > 10) {
      questions.push(aiInitialMessage.trim());
    }

    return questions;
  }, [aiInitialMessage]);

  // Effective questions to display: Solely rely on dynamic questions from Backend DB AI template
  const effectiveQuestions = useMemo(() => {
    const rawQuestions = parsedAiQuestions;
    const splittedQuestions = rawQuestions.flatMap(q => splitCompoundQuestion(q));

    // Deduplicate questions to prevent UI repetition
    const uniqueQuestions: string[] = [];
    const seenKeys = new Set<string>();

    for (const q of splittedQuestions) {
      // Clean string for comparison: remove non-alphanumeric, spaces, and make lowercase
      const cleanKey = q.replace(/[^a-zA-Z0-9\u00C0-\u1EF9]/g, '').toLowerCase();
      if (!seenKeys.has(cleanKey)) {
        seenKeys.add(cleanKey);
        uniqueQuestions.push(q);
      }
    }

    // Lọc bỏ câu hỏi về Hãng / Thương hiệu vì người bán đã chọn hoặc điền ở bước đầu tiên
    return uniqueQuestions.filter(q => {
      const lower = q.toLowerCase().trim();
      // Giữ lại các câu hỏi liên quan đến bảo hành (ví dụ: "Bảo hành chính hãng không")
      if (lower.includes('bảo hành')) return true;

      if (
        lower === 'hãng?' ||
        lower === 'hãng' ||
        lower.startsWith('hãng?') ||
        lower.startsWith('hãng:') ||
        lower.includes('hãng sản xuất') ||
        lower.includes('thương hiệu') ||
        lower.includes('nhà sản xuất') ||
        lower.includes('tên hãng') ||
        lower.includes('thuộc hãng nào') ||
        (lower.includes('hãng') && lower.length < 30)
      ) {
        return false;
      }
      return true;
    });
  }, [parsedAiQuestions]);

  // Questionnaire Answers State
  const [questionAnswers, setQuestionAnswers] = useState<Record<number, string>>({});
  const [isApplyingAnswers, setIsApplyingAnswers] = useState(false);
  const [isSubmittingAnswersToAi, setIsSubmittingAnswersToAi] = useState(false);
  const [applySuccessNotice, setApplySuccessNotice] = useState<string | null>(null);

  const answeredCount = useMemo(() => {
    return (Object.values(questionAnswers) as string[]).filter((v) => v && typeof v === 'string' && v.trim().length > 0).length;
  }, [questionAnswers]);

  const handleAnswerChange = (idx: number, val: string) => {
    setQuestionAnswers((prev) => ({ ...prev, [idx]: val }));
    const qText = effectiveQuestions[idx] || '';
    if (qText.toLowerCase().includes('thương hiệu') || qText.toLowerCase().includes('hãng')) {
      const cleanBrand = val.trim();
      if (cleanBrand && cleanBrand.length < 30) {
        setBrand(cleanBrand);
      }
    }
  };

  const handleApplyAnswersToDescription = () => {
    if (answeredCount === 0) {
      alert(lang === 'vi' ? 'Vui lòng điền câu trả lời cho ít nhất một câu hỏi trước khi áp dụng.' : 'Please answer at least one question before applying.');
      return;
    }
    setIsApplyingAnswers(true);
    const formattedAnswers = effectiveQuestions
      .map((q, idx) => {
        const ans = questionAnswers[idx]?.trim();
        if (!ans) return null;
        const parsed = parseQuestionItem(q, idx);
        return `• ${parsed.label}: ${ans}`;
      })
      .filter(Boolean)
      .join('\n');

    if (formattedAnswers) {
      const sectionHeader = '📋 Thông tin chi tiết sản phẩm:';
      let newDesc = description.trim();
      if (!newDesc) {
        newDesc = `${sectionHeader}\n${formattedAnswers}`;
      } else if (newDesc.includes(sectionHeader)) {
        const parts = newDesc.split(sectionHeader);
        newDesc = `${parts[0].trim()}\n\n${sectionHeader}\n${formattedAnswers}`.trim();
      } else {
        newDesc = `${newDesc}\n\n${sectionHeader}\n${formattedAnswers}`;
      }
      setDescription(newDesc);
      setApplySuccessNotice(lang === 'vi' ? 'Đã cập nhật câu trả lời vào phần Mô tả sản phẩm bên dưới!' : 'Updated answers into product description below!');
      setTimeout(() => setApplySuccessNotice(null), 4000);
    }
    setIsApplyingAnswers(false);
  };

  const handleSendAnswersToAi = async () => {
    if (answeredCount === 0) {
      alert(lang === 'vi' ? 'Vui lòng điền câu trả lời cho ít nhất một câu hỏi trước khi gửi cho AI.' : 'Please answer at least one question before sending to AI.');
      return;
    }
    if (!sessionId || !postId) {
      handleApplyAnswersToDescription();
      return;
    }

    setIsSubmittingAnswersToAi(true);
    const formattedAnswers = effectiveQuestions
      .map((q, idx) => {
        const ans = questionAnswers[idx]?.trim();
        if (!ans) return null;
        const parsed = parseQuestionItem(q, idx);
        return `${parsed.label}: ${ans}`;
      })
      .filter(Boolean)
      .join(', ');

    const promptMessage = `Tôi đã trả lời các câu hỏi về sản phẩm như sau: ${formattedAnswers}. Nhờ bạn viết lại một đoạn mô tả bán hàng thật chuyên nghiệp, trung thực và thu hút người mua nhé!`;

    try {
      const res = await aiChatService.chat(promptMessage, sessionId, postId);
      const reply = res?.reply || (res as any)?.message || '';
      if (reply) {
        setDescription(reply);
        setApplySuccessNotice(lang === 'vi' ? '✨ Trợ lý AI đã tổng hợp xong bài mô tả bán hàng và cập nhật vào ô Mô tả bên dưới!' : '✨ AI generated a new sales description and updated the description box below!');
        setTimeout(() => setApplySuccessNotice(null), 5000);
      } else {
        handleApplyAnswersToDescription();
      }
    } catch (err: any) {
      console.warn('Lỗi gửi câu trả lời cho AI chat:', err);
      handleApplyAnswersToDescription();
    } finally {
      setIsSubmittingAnswersToAi(false);
    }
  };

  const [userChatCount, setUserChatCount] = useState<number>(0);
  const [isSessionCompleted, setIsSessionCompleted] = useState<boolean>(false);

  // Step Loading States
  const [isInitializingPost, setIsInitializingPost] = useState(false);
  const [isSavingDraft, setIsSavingDraft] = useState(false);
  const [isAcceptingDescription, setIsAcceptingDescription] = useState(false);
  const [descriptionAccepted, setDescriptionAccepted] = useState(false);

  // AI Chat & Finalize states in Step 2
  const [chatMessages, setChatMessages] = useState<Array<{ role: 'ai' | 'user'; text: string; time: string }>>([]);
  const [chatInput, setChatInput] = useState('');
  const [isSendingChat, setIsSendingChat] = useState(false);
  const [isFinalizingChat, setIsFinalizingChat] = useState(false);

  // AI Valuation in Step 4
  const [isEstimatingPrice, setIsEstimatingPrice] = useState(false);
  const [valuationResult, setValuationResult] = useState<AiPriceEstimationResponse | null>(null);
  const [valuationHistory, setValuationHistory] = useState<any[]>([]);
  const [showValuationHistory, setShowValuationHistory] = useState(false);
  const [valuationRequestId, setValuationRequestId] = useState<string>('');

  // Submit in Step 5
  const [isSubmittingPost, setIsSubmittingPost] = useState(false);
  const [submitResult, setSubmitResult] = useState<PostSubmitResponse | null>(null);
  const [submitError, setSubmitError] = useState<string | null>(null);

  // Load Seller Credits
  const loadCredits = async () => {
    setIsLoadingCredits(true);
    try {
      const res = await sellerCreditService.getCredits();
      if (res) setCredits(res);
    } catch (err) {
      console.warn('Không tải được số dư credit:', err);
    } finally {
      setIsLoadingCredits(false);
    }
  };

  useEffect(() => {
    loadCredits();
  }, []);

  // Quick Purchase Credit for testing
  const handleQuickBuyCredit = async () => {
    setIsPurchasingCredits(true);
    try {
      await sellerCreditService.createPurchase({ listingQuantity: 2, valuationQuantity: 2 });
      alert(lang === 'vi' ? 'Đã tạo yêu cầu mua 2 LISTING & 2 VALUATION thành công!' : 'Created purchase request for 2 LISTING & 2 VALUATION!');
      await loadCredits();
    } catch (err: any) {
      alert('Mua credit thất bại: ' + (err?.message || 'Lỗi server'));
    } finally {
      setIsPurchasingCredits(false);
    }
  };

  // Load Categories on mount
  useEffect(() => {
    setIsLoadingCategories(true);
    categoryService.getCategories()
      .then((catList) => {
        if (Array.isArray(catList) && catList.length > 0) {
          setBackendCategories(catList);
          setSelectedCategoryId(catList[0].id);
        }
      })
      .catch((err) => console.error('Lỗi tải danh mục:', err))
      .finally(() => setIsLoadingCategories(false));
  }, []);

  // Load Items when category changes
  useEffect(() => {
    if (selectedCategoryId) {
      setIsLoadingItems(true);
      itemService.getItemsByCategory(selectedCategoryId)
        .then((itemList) => {
          if (Array.isArray(itemList) && itemList.length > 0) {
            setBackendItems(itemList);
            setSelectedItemId(itemList[0].id);
          } else {
            setBackendItems([]);
            setSelectedItemId('');
          }
        })
        .catch((err) => console.error('Lỗi tải items:', err))
        .finally(() => setIsLoadingItems(false));
    }
  }, [selectedCategoryId]);

  // Handle Photo File selection (multi-file or single-file)
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files: File[] = e.target.files ? (Array.from(e.target.files) as File[]) : [];
    if (files.length === 0) return;

    const remainingSlots = 6 - photoPreviews.length;
    const toAdd: File[] = files.slice(0, remainingSlots > 0 ? remainingSlots : 0);

    const newPreviews = toAdd.map((f: File) => URL.createObjectURL(f));
    setPhotoFiles((prev) => [...prev, ...toAdd]);
    setPhotoPreviews((prev) => [...prev, ...newPreviews]);
  };

  const handleRemovePhoto = (idx: number) => {
    setPhotoPreviews((prev) => prev.filter((_, i) => i !== idx));
    setPhotoFiles((prev) => prev.filter((_, i) => i !== idx));
  };

  // Convert URLs or files into Blob array for postService.initPost
  const prepareImageBlobs = async (): Promise<(File | Blob)[]> => {
    if (photoFiles.length >= 3) {
      return photoFiles.slice(0, 6);
    }
    // If user kept preview URLs (e.g. demo placeholders), fetch them as Blobs
    const blobs: (File | Blob)[] = [...photoFiles];
    for (const url of photoPreviews) {
      if (blobs.length >= 6) break;
      if (typeof url === 'string' && (url.startsWith('http://') || url.startsWith('https://'))) {
        try {
          const res = await fetch(url);
          const b = await res.blob();
          blobs.push(b);
        } catch {
          // ignore fetch fail
        }
      }
    }
    return blobs;
  };

  // =========================================================================
  // STEP 1: Init Post (POST /api/v1/posts/init with multipart/form-data)
  // =========================================================================
  const handleInitPost = async (mode: 'ai' | 'manual' = 'ai') => {
    if (!selectedCategoryId) {
      alert(lang === 'vi' ? 'Vui lòng chọn Danh mục sản phẩm' : 'Please select a Category');
      return;
    }
    if (photoPreviews.length < 3 || photoPreviews.length > 6) {
      alert(lang === 'vi' ? 'Vui lòng tải lên từ 3 đến 6 ảnh sản phẩm hợp lệ' : 'Please upload 3 to 6 product images');
      return;
    }

    setInitMode(mode);
    setPostMode(mode);
    setShowAiChatDrawer(mode === 'ai');
    setIsInitializingPost(true);
    try {
      const imageBlobs = await prepareImageBlobs();

      const initRes = await postService.initPost({
        categoryId: selectedCategoryId,
        itemId: selectedItemId || undefined,
        images: imageBlobs
      });

      if (initRes && initRes.postId) {
        setPostId(initRes.postId);
        setSessionId(initRes.sessionId);
        const initialAiDesc = initRes.aiInitialMessage || initRes.aiDescription || '';
        setAiInitialMessage(initialAiDesc);

        // Auto-generate title from selections if empty
        const selectedCat = backendCategories.find(c => c.id === selectedCategoryId);
        const selectedItm = backendItems.find(i => i.id === selectedItemId);
        const defaultTitle = `${brand ? brand + ' ' : ''}${model ? model + ' ' : ''}${selectedItm?.name || selectedCat?.name || 'Sản phẩm gia dụng'}`.trim();
        if (!title.trim() && defaultTitle) {
          setTitle(defaultTitle);
        }

        // Initialize draft state with data returned directly from BE initPost
        // Note: Do not overwrite description if initialAiDesc is purely an image warning or questionnaire template
        const isWarningOrQuestions =
          initialAiDesc.includes('ảnh quảng cáo') ||
          initialAiDesc.includes('ảnh catalog') ||
          initialAiDesc.includes('không phải ảnh chụp thực tế') ||
          initialAiDesc.includes('Vui lòng cung cấp');

        if (initialAiDesc && !description && mode === 'ai' && !isWarningOrQuestions) {
          setDescription(initialAiDesc);
        }

        setDraftPost({
          postId: initRes.postId,
          id: initRes.postId,
          title: defaultTitle,
          description: isWarningOrQuestions ? '' : initialAiDesc,
          aiDescription: initialAiDesc,
          descriptionAccepted: false,
          imageUrls: photoPreviews,
          status: 'DRAFT',
        });

        // Reset chat tracking
        setUserChatCount(0);
        setIsSessionCompleted(false);
        setQuestionAnswers({});

        // Initialize Chat messages with tailored questions
        // Use Backend AI's initial combined message directly
        let initialAiText = initRes.aiInitialMessage;
        if (!initialAiText) {
          initialAiText = lang === 'vi'
            ? `Chào bạn! Tôi là Trợ lý AI SecondLife. Đã nhận diện ${photoPreviews.length} ảnh của sản phẩm. Bạn vui lòng bổ sung thêm thông tin nhé.`
            : `Hello! I am SecondLife AI Assistant. Detected ${photoPreviews.length} photos. Please provide more details.`;
        }

        setChatMessages([
          {
            role: 'ai',
            text: initialAiText,
            time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
          }
        ]);

        setCurrentStep(2);
      } else {
        throw new Error('Hệ thống không trả về postId từ init');
      }
    } catch (err: any) {
      alert('Khởi tạo bài đăng thất bại: ' + (err?.message || 'Lỗi server'));
    } finally {
      setIsInitializingPost(false);
      setInitMode(null);
    }
  };

  // =========================================================================
  // STEP 2: Chat with AI & Finalize (POST /api/v1/ai/chat & /finalize-chat)
  // =========================================================================
  const handleSendChatMessage = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!chatInput.trim() || isSendingChat || !sessionId || !postId || isSessionCompleted) return;

    const userText = chatInput.trim();
    setChatInput('');
    setChatMessages((prev) => [
      ...prev,
      { role: 'user', text: userText, time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }
    ]);
    setUserChatCount((prev) => prev + 1);
    setIsSendingChat(true);

    try {
      const res = await aiChatService.chat(userText, sessionId, postId);
      const reply = res?.reply || (res as any)?.message || (lang === 'vi' ? 'Đã ghi nhận thông tin sản phẩm của bạn.' : 'Noted your item details.');
      setChatMessages((prev) => [
        ...prev,
        { role: 'ai', text: reply, time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }
      ]);
      // Tự động gán mô tả nếu người dùng chưa nhập tay
      if (!description.trim() && reply) {
        setDescription(reply);
      }
    } catch (err: any) {
      const errMsg = String(err?.message || '');
      let displayError = 'Lỗi phản hồi AI: ' + (errMsg || 'Vui lòng thử lại.');
      if (errMsg.includes('Chat limit exceeded') || errMsg.includes('credit')) {
        displayError = '⚠️ Bạn đã sử dụng hết 5 tin nhắn miễn phí của bài đăng này. Vui lòng nạp thêm Chat Credit để tiếp tục hoặc bấm "Tiếp tục: Xác nhận mô tả" để tiến hành đăng bài.';
      } else if (errMsg.includes('completed') || errMsg.includes('Conflict')) {
        setIsSessionCompleted(true);
        displayError = 'ℹ️ Phiên hội thoại này đã được tổng hợp thành mô tả sản phẩm. Bạn có thể chỉnh sửa trực tiếp ở ô mô tả bên trên.';
      }
      setChatMessages((prev) => [
        ...prev,
        { role: 'ai', text: displayError, time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }
      ]);
    } finally {
      setIsSendingChat(false);
    }
  };

  const handleFinalizeChatAndSync = async () => {
    if (!sessionId || !postId) return;
    setIsFinalizingChat(true);
    try {
      const finalizeRes = await postService.finalizeChat(sessionId);
      if (finalizeRes?.description) {
        setDescription(finalizeRes.description);
      }
      if (finalizeRes?.suggestedPrice) {
        const pNum = Number(finalizeRes.suggestedPrice);
        setFinalPriceVnd(pNum);
        setValuationResult({
          fairPriceMin: Math.round(pNum * 0.85),
          fairPriceMax: Math.round(pNum * 1.15),
          suggestedPrice: pNum,
          modelVersion: 'SecondLife-AI-v2.1',
          expectedSellTime: '3-5 ngày',
          createdAt: new Date().toISOString()
        });
      }
      setIsSessionCompleted(true);
      alert(lang === 'vi' ? 'AI đã tổng hợp cuộc hội thoại và cập nhật mô tả thành công!' : 'AI summarized the chat into your description!');
    } catch (err: any) {
      alert('Hoàn tất chat thất bại: ' + (err?.message || 'Lỗi kết nối'));
    } finally {
      setIsFinalizingChat(false);
    }
  };

  const handleGoToStep3 = async () => {
    let currentTitle = title.trim();
    let currentDesc = description.trim();

    // 1. Tự động sinh tiêu đề nếu người dùng chưa nhập
    if (!currentTitle) {
      const selectedCat = backendCategories.find(c => c.id === selectedCategoryId);
      const selectedItm = backendItems.find(i => i.id === selectedItemId);
      currentTitle = `${brand ? brand + ' ' : ''}${model ? model + ' ' : ''}${selectedItm?.name || selectedCat?.name || 'Sản phẩm gia dụng'}`.trim();
      setTitle(currentTitle);
    }

    // 1.5. Tự động đồng bộ các câu trả lời từ bảng câu hỏi AI vào mô tả
    const currentAnsweredCount = (Object.values(questionAnswers) as string[]).filter((v) => v && typeof v === 'string' && v.trim().length > 0).length;
    if (currentAnsweredCount > 0) {
      const answersText = effectiveQuestions
        .map((q, idx) => {
          const ans = questionAnswers[idx]?.trim();
          if (!ans) return null;
          const parsed = parseQuestionItem(q, idx);
          return `• ${parsed.label}: ${ans}`;
        })
        .filter(Boolean)
        .join('\n');
      if (answersText) {
        const sectionHeader = '📋 Thông tin chi tiết sản phẩm:';
        if (!currentDesc) {
          currentDesc = `${sectionHeader}\n${answersText}`;
          setDescription(currentDesc);
        } else if (!currentDesc.includes(sectionHeader)) {
          currentDesc = `${currentDesc}\n\n${sectionHeader}\n${answersText}`;
          setDescription(currentDesc);
        }
      }
    }

    // 2. Tự động lấy mô tả từ tin nhắn AI gần nhất hoặc gợi ý ban đầu
    if (!currentDesc) {
      const lastAiMsg = [...chatMessages].reverse().find(m => m.role === 'ai' && !m.text.startsWith('Lỗi'));
      if (lastAiMsg?.text) {
        currentDesc = lastAiMsg.text;
        setDescription(currentDesc);
      } else if (aiInitialMessage) {
        currentDesc = aiInitialMessage;
        setDescription(currentDesc);
      }
    }

    // 3. Nếu vẫn chưa có và có phiên chat, gọi finalizeChat từ BE để tổng hợp
    if (!currentDesc && sessionId && postId) {
      try {
        setIsFinalizingChat(true);
        const finalizeRes = await postService.finalizeChat(sessionId);
        if (finalizeRes?.description) {
          currentDesc = finalizeRes.description;
          setDescription(finalizeRes.description);
        }
        if (finalizeRes?.suggestedPrice) {
          const pNum = Number(finalizeRes.suggestedPrice);
          setFinalPriceVnd(pNum);
          setValuationResult({
            fairPriceMin: Math.round(pNum * 0.85),
            fairPriceMax: Math.round(pNum * 1.15),
            suggestedPrice: pNum,
            modelVersion: 'SecondLife-AI-v2.1',
            expectedSellTime: '3-5 ngày',
            createdAt: new Date().toISOString()
          });
        }
        setIsSessionCompleted(true);
      } catch (err) {
        console.warn('Auto finalize chat warning:', err);
      } finally {
        setIsFinalizingChat(false);
      }
    }

    if (!currentTitle) {
      alert(lang === 'vi' ? 'Vui lòng nhập Tiêu đề bài đăng.' : 'Please enter Listing Title.');
      return;
    }
    if (!currentDesc) {
      alert(lang === 'vi' ? 'Vui lòng nhập Mô tả sản phẩm hoặc trò chuyện với AI để tạo mô tả.' : 'Please provide a Description or chat with AI.');
      return;
    }

    setCurrentStep(3);
  };

  // =========================================================================
  // STEP 3: Save Draft & Accept Description (PUT /draft & POST /accept-description)
  // =========================================================================
  const handleSaveAndAcceptDescription = async () => {
    if (!postId) return;
    if (!title.trim()) {
      alert(lang === 'vi' ? 'Vui lòng nhập Tiêu đề bài đăng' : 'Please enter Title');
      return;
    }
    if (!description.trim()) {
      alert(lang === 'vi' ? 'Vui lòng nhập hoặc áp dụng Mô tả sản phẩm' : 'Please enter Description');
      return;
    }

    setIsAcceptingDescription(true);
    try {
      // 1. PUT /api/v1/posts/{postId}/draft
      await postService.updateDraft(postId, {
        title: title.trim(),
        description: description.trim(),
        itemCondition: itemCondition || 'USED',
        price: null
      });

      // 2. POST /api/v1/posts/{postId}/accept-description
      const acceptRes = await postService.acceptDescription(postId, description.trim());
      setDescriptionAccepted(true);
      setDraftPost(acceptRes);

      // Successfully confirmed description -> Advance to Step 4
      setCurrentStep(4);
    } catch (err: any) {
      alert('Xác nhận mô tả thất bại: ' + (err?.message || 'Lỗi server'));
    } finally {
      setIsAcceptingDescription(false);
    }
  };

  // =========================================================================
  // STEP 4: AI Price Estimation (POST /ai-price-estimation - Trừ 1 VALUATION)
  // =========================================================================
  const handleRunAiValuation = async () => {
    if (!postId) return;
    setIsEstimatingPrice(true);
    const reqId = typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : `req-${Date.now()}`;
    setValuationRequestId(reqId);

    try {
      const res = await postService.estimatePrice(postId, reqId);
      setValuationResult(res);
      if (res.suggestedPrice) {
        setFinalPriceVnd(res.suggestedPrice);
      }
      // Re-fetch credits to reflect deduction of 1 VALUATION
      await loadCredits();
    } catch (err: any) {
      alert('Định giá AI thất bại: ' + (err?.message || 'Lỗi kết nối tới dịch vụ AI'));
    } finally {
      setIsEstimatingPrice(false);
    }
  };

  const handleLoadValuationHistory = async () => {
    if (!postId) return;
    try {
      const hist = await postService.getPriceEstimateHistory(postId, 0, 10);
      const items = hist?.items || hist?.content || (Array.isArray(hist) ? hist : []);
      setValuationHistory(items);
      setShowValuationHistory(true);
    } catch (err: any) {
      alert('Không thể tải lịch sử định giá: ' + (err?.message || ''));
    }
  };

  // =========================================================================
  // STEP 5: Final Submit (POST /api/v1/posts/submit/{postId})
  // =========================================================================
  const handleSubmitPostFinal = async () => {
    if (!postId) return;
    if (!finalPriceVnd || finalPriceVnd < 1000) {
      alert(lang === 'vi' ? 'Vui lòng nhập giá bán hợp lệ (tối thiểu 1.000 đ)' : 'Please enter valid price');
      return;
    }

    setIsSubmittingPost(true);
    setSubmitError(null);
    try {
      const submitRes = await postService.submitPost(postId, {
        title: title.trim(),
        description: description.trim(),
        price: finalPriceVnd
      });

      setSubmitResult(submitRes);
      // Reload credits (if ACTIVE, minus 1 LISTING)
      await loadCredits();
    } catch (err: any) {
      setSubmitError(err?.message || 'Gửi bài đăng thất bại');
    } finally {
      setIsSubmittingPost(false);
    }
  };

  const handleFinishAndExit = () => {
    if (!postId) return;
    const catName = backendCategories.find((c) => c.id === selectedCategoryId)?.name || 'Thiết bị điện tử';
    const newListing: Listing = {
      id: postId,
      title: title || 'Sản phẩm SecondLife',
      category: catName as ItemCategory,
      brand: brand || 'Hãng',
      model: model || 'Model',
      purchaseYear,
      priceVnd: finalPriceVnd,
      originalPriceVnd: finalPriceVnd * 1.3,
      conditionGrade: 'Like New',
      declaredConditionText: itemCondition,
      description: description || 'Mô tả bài đăng đã qua kiểm duyệt AI',
      location: 'Hà Nội / TP.HCM',
      sellerId: 'current-user',
      sellerName: 'Người bán SecondLife',
      sellerRating: 5.0,
      sellerCompletedOrders: 1,
      sellerVerified: true,
      status: (submitResult?.status === 'ACTIVE' ? 'active' : 'pending') as any,
      createdAt: new Date().toISOString(),
      isInspectionGuaranteed: finalPriceVnd > 5000000,
      requiresInspection: finalPriceVnd > 5000000,
      photos: {
        front: photoPreviews[0] || '',
        back: photoPreviews[1] || '',
        screenOrDetails: photoPreviews[2] || '',
        accessoriesOrBox: photoPreviews[3] || '',
        serialOrReceipt: photoPreviews[4] || '',
        extraDetail: photoPreviews[5] || ''
      },
      photoGallery: photoPreviews
    };
    onListingCreated(newListing);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-20 px-4 sm:px-6">
      {/* Top Banner: Credit Status Bar & Navigation */}
      <div className="bg-[#24263e] text-white rounded-3xl p-5 shadow-lg border border-slate-700 flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-2xl bg-[#c34c36] text-white flex items-center justify-center shadow-md shrink-0">
            <Coins className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-base font-black tracking-wide">
                {lang === 'vi' ? 'Hệ Thống Đăng Tin & Định Giá AI (Main Flow 1)' : 'AI Listing & Valuation Pipeline'}
              </h2>
              <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 uppercase">
                Backend Live
              </span>
            </div>
            <div className="flex flex-wrap items-center gap-3 text-xs text-slate-300 mt-1">
              <span>Số dư Credit của bạn:</span>
              <span className="px-2.5 py-0.5 rounded-lg bg-white/10 font-mono font-bold text-amber-300 flex items-center gap-1 border border-white/10">
                <span>🎯 {credits?.listing ?? 0}</span>
                <span className="text-[10px] text-slate-400">LISTING</span>
              </span>
              <span className="px-2.5 py-0.5 rounded-lg bg-white/10 font-mono font-bold text-cyan-300 flex items-center gap-1 border border-white/10">
                <span>💡 {credits?.valuation ?? 0}</span>
                <span className="text-[10px] text-slate-400">VALUATION</span>
              </span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          <button
            onClick={handleQuickBuyCredit}
            disabled={isPurchasingCredits}
            className="px-3.5 py-2 rounded-xl bg-white/10 hover:bg-white/20 text-xs font-bold text-white border border-white/20 transition cursor-pointer flex items-center gap-1.5"
            title="Tạo đơn mua 2 LISTING + 2 VALUATION"
          >
            {isPurchasingCredits ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Plus className="w-3.5 h-3.5 text-amber-300" />}
            <span>{lang === 'vi' ? 'Nạp thêm Credit' : 'Buy Credits'}</span>
          </button>
          <button
            onClick={onCancel}
            className="px-3.5 py-2 rounded-xl bg-white/5 hover:bg-white/10 text-xs font-bold text-slate-300 hover:text-white border border-white/10 transition cursor-pointer"
          >
            {lang === 'vi' ? 'Hủy bỏ' : 'Cancel'}
          </button>
        </div>
      </div>

      {/* Pipeline Step Progress Bar (5 Steps) */}
      <div className="bg-white rounded-2xl p-4 shadow-sm border border-gray-200">
        <div className="grid grid-cols-2 md:grid-cols-5 gap-2 text-xs font-bold">
          {[
            { step: 1, label: '1. Sản Phẩm & 3-6 Ảnh' },
            { step: 2, label: '2. Mô Tả AI & Chat' },
            { step: 3, label: '3. Xác Nhận Mô Tả' },
            { step: 4, label: '4. Định Giá AI' },
            { step: 5, label: '5. Gửi Đăng Bài' }
          ].map((s) => {
            const isActive = currentStep === s.step;
            const isDone = currentStep > s.step;
            return (
              <div
                key={s.step}
                className={`py-2 px-3 rounded-xl flex items-center gap-2 border transition ${isActive
                  ? 'bg-[#24263e] text-white border-[#24263e] shadow-xs'
                  : isDone
                    ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                    : 'bg-slate-50 text-slate-400 border-slate-100'
                  }`}
              >
                <div
                  className={`w-5 h-5 rounded-full flex items-center justify-center text-[10px] font-black shrink-0 ${isActive
                    ? 'bg-[#c34c36] text-white'
                    : isDone
                      ? 'bg-emerald-600 text-white'
                      : 'bg-slate-200 text-slate-600'
                    }`}
                >
                  {isDone ? <Check className="w-3 h-3" /> : s.step}
                </div>
                <span className="truncate">{s.label}</span>
              </div>
            );
          })}
        </div>
      </div>

      {/* ========================================================================= */}
      {/* STEP 1: CHỌN DANH MỤC, VẬT PHẨM & TẢI 3-6 ẢNH SẢN PHẨM                   */}
      {/* ========================================================================= */}
      {currentStep === 1 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-gray-200 shadow-sm space-y-6">
          <div>
            <h3 className="text-lg font-black text-[#24263e] flex items-center gap-2">
              <Camera className="w-5 h-5 text-[#c34c36]" />
              <span>{lang === 'vi' ? 'Bước 1: Chọn Danh Mục Sản Phẩm & Tải 3-6 Ảnh' : 'Step 1: Select Category & Upload 3-6 Photos'}</span>
            </h3>
            <p className="text-xs text-slate-500 mt-1">
              AI sẽ phân tích toàn bộ ảnh cùng danh mục sản phẩm để tạo mô tả và gợi ý định giá chuẩn xác.
            </p>
          </div>

          {/* Category & Item Dropdowns */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-[#24263e]">
                {lang === 'vi' ? 'Danh Mục Sản Phẩm (Category) *' : 'Product Category *'}
              </label>
              <select
                value={selectedCategoryId}
                onChange={(e) => setSelectedCategoryId(e.target.value)}
                disabled={isLoadingCategories}
                className="w-full px-3.5 py-2.5 bg-slate-50 border border-gray-200 rounded-xl text-xs font-bold text-[#24263e] focus:outline-none focus:border-[#c34c36]"
              >
                {backendCategories.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.name}
                  </option>
                ))}
              </select>
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-bold text-[#24263e]">
                {lang === 'vi' ? 'Loại Thiết Bị (Item/Model thuộc Category)' : 'Item Type'}
              </label>
              <select
                value={selectedItemId}
                onChange={(e) => setSelectedItemId(e.target.value)}
                disabled={isLoadingItems || backendItems.length === 0}
                className="w-full px-3.5 py-2.5 bg-slate-50 border border-gray-200 rounded-xl text-xs font-bold text-[#24263e] focus:outline-none focus:border-[#c34c36]"
              >
                {backendItems.length > 0 ? (
                  backendItems.map((i) => (
                    <option key={i.id} value={i.id}>
                      {i.name}
                    </option>
                  ))
                ) : (
                  <option value="">{isLoadingItems ? 'Đang tải vật phẩm...' : 'Chung theo danh mục'}</option>
                )}
              </select>
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-bold text-[#24263e]">Thương hiệu (Brand) *</label>
              <input
                type="text"
                value={brand}
                onChange={(e) => setBrand(e.target.value)}
                placeholder="VD: Panasonic, Toshiba, LG, Sony, Apple..."
                className="w-full px-3.5 py-2.5 bg-slate-50 border border-gray-200 rounded-xl text-xs text-[#24263e] focus:outline-none focus:border-[#c34c36]"
              />
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-bold text-[#24263e]">Năm sản xuất / Mua</label>
              <input
                type="number"
                value={purchaseYear}
                onChange={(e) => setPurchaseYear(Number(e.target.value))}
                min={2018}
                max={2026}
                className="w-full px-3.5 py-2.5 bg-slate-50 border border-gray-200 rounded-xl text-xs text-[#24263e] focus:outline-none focus:border-[#c34c36]"
              />
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-bold text-[#24263e]">Giá sản phẩm lúc mua (VNĐ)</label>
              <input
                type="text"
                value={originalPriceVnd ? formatVndInput(originalPriceVnd.toString()) : ''}
                onChange={(e) => {
                  const raw = e.target.value.replace(/\D/g, '');
                  setOriginalPriceVnd(raw ? Number(raw) : '');
                }}
                placeholder="VD: 5.000.000"
                className="w-full px-3.5 py-2.5 bg-slate-50 border border-gray-200 rounded-xl text-xs text-[#24263e] focus:outline-none focus:border-[#c34c36]"
              />
              {originalPriceVnd !== '' && (
                <p className="text-[11px] text-emerald-600 font-medium italic">
                  {numberToVietnameseWords(Number(originalPriceVnd))}
                </p>
              )}
            </div>
          </div>

          {/* Photo Checklist 3-6 Photos */}
          <div className="space-y-3 pt-2 border-t border-gray-100">
            <div>
              <label className="text-xs font-bold text-[#24263e] flex items-center gap-2">
                <span>Ảnh chụp sản phẩm thực tế (Yêu cầu 3 - 6 ảnh) *</span>
                <span
                  className={`text-[10px] font-black px-2 py-0.5 rounded-full ${photoPreviews.length >= 3 && photoPreviews.length <= 6
                    ? 'bg-emerald-100 text-emerald-800'
                    : photoPreviews.length === 0
                      ? 'bg-slate-100 text-slate-600'
                      : 'bg-rose-100 text-rose-800'
                    }`}
                >
                  Đã có: {photoPreviews.length}/6 ảnh
                </span>
              </label>
              <p className="text-[11px] text-slate-500 mt-0.5">
                Tải lên mặt trước, mặt sau, góc cạnh, tem nhãn/seri và phụ kiện để AI định giá tối ưu.
              </p>
            </div>

            {/* Photos Preview Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 gap-3">
              {photoPreviews.map((previewUrl, idx) => (
                <div key={idx} className="relative group rounded-2xl overflow-hidden border border-gray-200 aspect-square bg-slate-100 shadow-xs">
                  <img src={previewUrl} alt={`Ảnh ${idx + 1}`} className="w-full h-full object-cover" />
                  <div className="absolute top-1 left-1 px-1.5 py-0.5 rounded-md bg-black/60 text-white text-[10px] font-bold">
                    #{idx + 1}
                  </div>
                  <button
                    type="button"
                    onClick={() => handleRemovePhoto(idx)}
                    className="absolute top-1 right-1 w-6 h-6 rounded-full bg-rose-600 text-white flex items-center justify-center opacity-80 hover:opacity-100 transition shadow-sm cursor-pointer"
                    title="Xóa ảnh"
                  >
                    <X className="w-3.5 h-3.5" />
                  </button>
                </div>
              ))}

              {photoPreviews.length < 6 && (
                <label className="border-2 border-dashed border-gray-300 hover:border-[#c34c36] rounded-2xl flex flex-col items-center justify-center gap-1.5 aspect-square bg-slate-50 hover:bg-slate-100 transition cursor-pointer text-slate-500 text-center p-2 group shadow-xs">
                  <div className="w-9 h-9 rounded-full bg-white border border-gray-200 flex items-center justify-center group-hover:scale-105 group-hover:border-[#c34c36] transition shadow-xs">
                    <Camera className="w-4.5 h-4.5 text-slate-500 group-hover:text-[#c34c36] transition" />
                  </div>
                  <span className="text-[11px] font-bold text-slate-600 group-hover:text-[#c34c36] transition">+ Thêm ảnh</span>
                  <input
                    type="file"
                    multiple
                    accept="image/jpeg,image/png,image/webp"
                    className="hidden"
                    onChange={handleFileChange}
                  />
                </label>
              )}
            </div>
          </div>

          {/* Action Buttons: Tự Đăng Bài & Chat Với AI */}
          <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 pt-4 border-t border-gray-100">
            <div className="text-xs text-slate-500 font-medium">
              <span>Đã chọn: <strong>{photoPreviews.length}/6 ảnh</strong>. Bạn có thể chọn tự điền thông tin hoặc để AI hỗ trợ.</span>
            </div>

            <div className="flex items-center gap-3">
              {/* Nút 1: Tự đăng bài */}
              <button
                type="button"
                onClick={() => handleInitPost('manual')}
                disabled={isInitializingPost || photoPreviews.length < 3 || photoPreviews.length > 6}
                className="px-6 py-3.5 rounded-2xl font-black text-xs sm:text-sm shadow-xs flex items-center justify-center gap-2 transition cursor-pointer border-2 border-[#24263e]/20 bg-white text-[#24263e] hover:bg-slate-50 hover:border-[#24263e] active:scale-[0.99] disabled:opacity-50 disabled:cursor-not-allowed"
                title="Tự nhập tiêu đề, mô tả và đăng bài nhanh chóng"
              >
                {isInitializingPost && initMode === 'manual' ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin text-[#c34c36]" />
                    <span>Đang khởi tạo...</span>
                  </>
                ) : (
                  <>
                    <PenLine className="w-4 h-4 text-[#c34c36]" />
                    <span>Tự Đăng Bài</span>
                    <ArrowRight className="w-3.5 h-3.5 opacity-60" />
                  </>
                )}
              </button>

              {/* Nút 2: Chat với AI */}
              <button
                type="button"
                onClick={() => handleInitPost('ai')}
                disabled={isInitializingPost || photoPreviews.length < 3 || photoPreviews.length > 6}
                className="px-7 py-3.5 rounded-2xl font-black text-xs sm:text-sm shadow-md flex items-center justify-center gap-2.5 transition cursor-pointer bg-gradient-to-r from-[#c34c36] to-[#24263e] text-white hover:opacity-95 active:scale-[0.99] disabled:opacity-50 disabled:cursor-not-allowed"
                title="Sử dụng trí tuệ nhân tạo để phân tích ảnh và hoàn thiện mô tả"
              >
                {isInitializingPost && initMode === 'ai' ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin text-amber-300" />
                    <span>AI đang phân tích ảnh...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 text-amber-300" />
                    <span>Chat Với AI</span>
                    <ArrowRight className="w-4 h-4" />
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* STEP 2: MÔ TẢ AI, CHỈNH SỬA & TRỢ LÝ CHAT BỔ SUNG                         */}
      {/* ========================================================================= */}
      {currentStep === 2 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-gray-200 shadow-sm space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <h3 className="text-lg font-black text-[#24263e] flex items-center gap-2">
                {postMode === 'ai' ? (
                  <>
                    <Bot className="w-5 h-5 text-[#c34c36]" />
                    <span>{lang === 'vi' ? 'Bước 2: Hoàn Thiện Mô Tả Cùng Trợ Lý AI' : 'Step 2: AI Description & Chat'}</span>
                  </>
                ) : (
                  <>
                    <PenLine className="w-5 h-5 text-[#c34c36]" />
                    <span>{lang === 'vi' ? 'Bước 2: Tự Nhập Tiêu Đề & Mô Tả Sản Phẩm' : 'Step 2: Manual Title & Description'}</span>
                  </>
                )}
              </h3>
              <p className="text-xs text-slate-500 mt-1">
                {postMode === 'ai'
                  ? (lang === 'vi' ? 'Trò chuyện với Trợ lý AI để tự động hoàn thiện mô tả hoặc chỉnh sửa trực tiếp bên dưới.' : 'Chat with AI Assistant to refine your description or edit directly below.')
                  : (lang === 'vi' ? 'Bạn đang ở chế độ tự đăng bài. Nhập tiêu đề, mô tả và tình trạng của sản phẩm để tiếp tục.' : 'Manual mode: Enter title, description, and item condition to proceed.')}
              </p>
            </div>

            {/* Mode Switcher Pill */}
            <div className="flex items-center gap-1.5 p-1 bg-slate-100 rounded-xl shrink-0 self-start sm:self-auto">
              <button
                type="button"
                onClick={() => {
                  setPostMode('manual');
                  setShowAiChatDrawer(false);
                }}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold transition cursor-pointer flex items-center gap-1.5 ${postMode === 'manual' ? 'bg-white text-[#24263e] shadow-xs' : 'text-slate-500 hover:text-slate-800'}`}
              >
                <PenLine className="w-3.5 h-3.5" />
                <span>Tự đăng bài</span>
              </button>
              <button
                type="button"
                onClick={() => {
                  setPostMode('ai');
                  setShowAiChatDrawer(true);
                }}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold transition cursor-pointer flex items-center gap-1.5 ${postMode === 'ai' ? 'bg-[#c34c36] text-white shadow-xs' : 'text-slate-500 hover:text-slate-800'}`}
              >
                <Sparkles className="w-3.5 h-3.5" />
                <span>Chat với AI</span>
              </button>
            </div>
          </div>

          {/* AI Vision Warning: Catalog / Promotional Photo Detected */}
          {isCatalogPhotoWarning && (
            <div className="p-4 rounded-2xl bg-amber-50 border border-amber-300 text-amber-950 flex items-start gap-3 shadow-xs animate-fadeIn">
              <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
              <div className="space-y-1 text-xs">
                <div className="font-black text-amber-900 uppercase flex items-center gap-1.5 text-[11px]">
                  <span>Nhận định từ AI Thị Giác (Llava Vision)</span>
                  <span className="px-2 py-0.5 rounded-full bg-amber-200 text-amber-900 font-bold text-[10px]">Ảnh catalog / quảng cáo</span>
                </div>
                <p className="leading-relaxed text-slate-700">
                  Hình ảnh bạn cung cấp là <strong>ảnh quảng cáo kỹ thuật số (ảnh catalog)</strong>, không phải ảnh chụp thực tế. Hệ thống AI chưa có cơ sở đánh giá độ hao mòn và tình trạng thực tế của sản phẩm.
                </p>
                <p className="text-[11px] text-amber-800 font-medium">
                  💡 <em>Khuyến nghị:</em> Hãy trả lời các câu hỏi bên dưới hoặc gửi ảnh thực tế qua chat để AI định giá chính xác và viết bài chuẩn nhất.
                </p>
              </div>
            </div>
          )}

          {/* AI Initial Description Suggestion Box (Only shown if AI produced an actual description and not just warning/questions) */}
          {aiInitialMessage && !isCatalogPhotoWarning && parsedAiQuestions.length === 0 && (
            <div className="p-4 rounded-2xl bg-amber-50/70 border border-amber-200 text-slate-800 text-xs space-y-2">
              <div className="flex items-center justify-between">
                <span className="font-black text-[#24263e] flex items-center gap-1.5 uppercase text-[11px]">
                  <Sparkles className="w-4 h-4 text-amber-600" />
                  Gợi ý mô tả từ Gemini / Ollama AI:
                </span>
                <button
                  type="button"
                  onClick={() => setDescription(aiInitialMessage)}
                  className="px-3 py-1 rounded-lg bg-[#24263e] hover:bg-black text-white text-[11px] font-bold transition cursor-pointer"
                >
                  Dùng mô tả này
                </button>
              </div>
              <p className="whitespace-pre-wrap leading-relaxed text-slate-700 italic">
                "{aiInitialMessage}"
              </p>
            </div>
          )}

          {/* Interactive AI Questionnaire: Hiện các câu hỏi cần người dùng trả lời và dưới mỗi câu thì hiện chỗ để điền */}
          {effectiveQuestions.length > 0 && (
            <div className="bg-gradient-to-br from-amber-50/90 via-orange-50/30 to-white rounded-3xl p-5 sm:p-6 border-2 border-amber-200/90 shadow-xs space-y-5">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-amber-200/70 pb-4">
                <div>
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="px-3 py-1 rounded-full bg-gradient-to-r from-amber-500 to-[#c34c36] text-white font-black text-xs flex items-center gap-1.5 shadow-xs">
                      <Sparkles className="w-3.5 h-3.5 text-amber-200" />
                      <span>{lang === 'vi' ? 'Khảo Sát Chi Tiết Sản Phẩm Cùng AI' : 'AI Product Questionnaire'}</span>
                    </span>
                    <span className="text-xs font-extrabold text-[#24263e]">
                      {currentCategory?.name || 'Sản phẩm'} • {currentItem?.name || 'Thiết bị'}
                    </span>
                    {brand && (
                      <span className="text-xs font-bold text-slate-700 bg-white px-2 py-0.5 rounded-md border border-gray-200">
                        {brand}
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-slate-600 mt-1.5 leading-relaxed">
                    {lang === 'vi'
                      ? 'AI đã quét hình ảnh và phân tích danh mục. Hãy điền câu trả lời bên dưới mỗi câu hỏi để hệ thống định giá chính xác và tự động hoàn thiện mô tả.'
                      : 'AI analyzed your uploaded photos. Please fill in the answers under each question to help AI generate an accurate valuation and description.'}
                  </p>
                </div>

                {/* Progress Indicator */}
                <div className="flex items-center gap-2.5 bg-white px-3.5 py-2 rounded-2xl border border-amber-200 shadow-2xs self-start sm:self-auto shrink-0">
                  <div className="text-right">
                    <div className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Tiến độ điền</div>
                    <div className="text-xs font-black text-[#c34c36]">
                      {answeredCount}/{effectiveQuestions.length} câu đã trả lời
                    </div>
                  </div>
                  <div className="w-10 h-10 rounded-xl bg-amber-100 text-amber-900 font-black text-xs flex items-center justify-center border border-amber-300">
                    {Math.round((answeredCount / (effectiveQuestions.length || 1)) * 100)}%
                  </div>
                </div>
              </div>

              {/* Progress Bar */}
              <div className="w-full bg-amber-100/70 rounded-full h-2 overflow-hidden">
                <div
                  className="bg-gradient-to-r from-amber-500 via-orange-500 to-[#c34c36] h-full transition-all duration-300 rounded-full"
                  style={{ width: `${Math.round((answeredCount / (effectiveQuestions.length || 1)) * 100)}%` }}
                />
              </div>

              {/* Notice Message */}
              {applySuccessNotice && (
                <div className="p-3 bg-emerald-50 border border-emerald-300 text-emerald-900 text-xs font-bold rounded-2xl flex items-center gap-2 animate-fadeIn shadow-2xs">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                  <span>{applySuccessNotice}</span>
                </div>
              )}

              {/* List of Questions with Input Fields Underneath */}
              <div className="grid grid-cols-1 gap-3.5">
                {effectiveQuestions.map((q, idx) => {
                  const parsed = parseQuestionItem(q, idx);
                  const currentVal = questionAnswers[idx] || '';
                  const hasAnswer = currentVal.trim().length > 0;

                  return (
                    <div
                      key={idx}
                      className={`p-4 rounded-2xl border transition-all ${hasAnswer
                          ? 'bg-white border-emerald-300 shadow-xs'
                          : 'bg-white/85 border-amber-200/90 hover:border-amber-400 shadow-2xs'
                        }`}
                    >
                      {/* Tiêu đề & Số thứ tự */}
                      <div className="flex items-start justify-between gap-3 mb-2">
                        <div className="flex items-start gap-2.5">
                          <span
                            className={`w-6 h-6 rounded-lg font-black text-xs flex items-center justify-center shrink-0 mt-0.5 ${hasAnswer ? 'bg-emerald-600 text-white shadow-2xs' : 'bg-[#24263e] text-white'
                              }`}
                          >
                            {hasAnswer ? <Check className="w-3.5 h-3.5" /> : idx + 1}
                          </span>
                          <div>
                            <h4 className="text-xs font-black text-[#24263e] leading-snug">
                              {parsed.label}
                            </h4>
                            {parsed.hint && (
                              <p className="text-[11px] text-slate-500 italic mt-0.5">
                                {parsed.hint}
                              </p>
                            )}
                          </div>
                        </div>

                        {hasAnswer && (
                          <span className="text-[10px] font-bold px-2 py-0.5 rounded-md bg-emerald-100 text-emerald-800 shrink-0 flex items-center gap-1">
                            <Check className="w-3 h-3" /> Đã điền
                          </span>
                        )}
                      </div>

                      {/* Các nút bấm Gợi ý nhanh (+ 6 tháng, + 1 năm...) */}
                      {parsed.examples.length > 0 && (
                        <div className="flex items-center gap-1.5 flex-wrap mb-2 sm:pl-8">
                          <span className="text-[10px] text-slate-400 font-bold">Gợi ý nhanh:</span>
                          {parsed.examples.map((ex, exIdx) => (
                            <button
                              key={exIdx}
                              type="button"
                              onClick={() => handleAnswerChange(idx, ex)}
                              className={`px-2.5 py-0.5 rounded-lg text-[10px] font-bold border transition cursor-pointer ${currentVal === ex
                                  ? 'bg-[#c34c36] text-white border-[#c34c36]'
                                  : 'bg-amber-50 hover:bg-amber-100 text-amber-900 border-amber-200'
                                }`}
                              title={`Bấm để điền nhanh "${ex}"`}
                            >
                              + {ex}
                            </button>
                          ))}
                        </div>
                      )}

                      {/* Ô Input nhập câu trả lời */}
                      <div className="sm:pl-8">
                        <div className="relative">
                          <input
                            type="text"
                            value={currentVal}
                            onChange={(e) => handleAnswerChange(idx, e.target.value)}
                            placeholder={
                              parsed.examples.length > 0
                                ? `VD: ${parsed.examples.slice(0, 3).join(', ')}...`
                                : 'Nhập câu trả lời cho câu hỏi này...'
                            }
                            className="w-full px-4 py-2.5 bg-slate-50 hover:bg-white focus:bg-white border border-gray-200 focus:border-[#c34c36] rounded-xl text-xs font-semibold text-[#24263e] focus:outline-none transition shadow-2xs"
                          />
                          {currentVal && (
                            <button
                              type="button"
                              onClick={() => handleAnswerChange(idx, '')}
                              className="absolute right-2.5 top-1/2 -translate-y-1/2 w-5 h-5 rounded-full bg-slate-200 hover:bg-slate-300 text-slate-600 flex items-center justify-center text-xs cursor-pointer transition"
                              title="Xóa câu trả lời"
                            >
                              ✕
                            </button>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Bottom Action Bar for Questionnaire */}
              <div className="mt-4 pt-3.5 border-t border-amber-200/80 flex flex-col sm:flex-row items-center justify-between gap-3">
                <div className="text-xs text-slate-600 flex items-center gap-1.5 self-start sm:self-auto">
                  <Sparkles className="w-4 h-4 text-amber-600 shrink-0" />
                  <span>
                    {answeredCount > 0
                      ? `Đã điền ${answeredCount}/${effectiveQuestions.length} câu trả lời. Bấm nút để AI viết bài mô tả hoàn chỉnh:`
                      : 'Hãy trả lời các câu hỏi phía trên để AI hỗ trợ viết bài mô tả chuẩn xác nhất.'}
                  </span>
                </div>

                <div className="flex items-center gap-2 w-full sm:w-auto">
                  <button
                    type="button"
                    onClick={handleApplyAnswersToDescription}
                    disabled={answeredCount === 0 || isApplyingAnswers}
                    className="flex-1 sm:flex-none px-3.5 py-2.5 rounded-xl border border-amber-300 bg-white hover:bg-amber-50 text-amber-900 text-xs font-bold transition disabled:opacity-40 cursor-pointer"
                    title="Chèn nguyên văn câu trả lời vào mô tả"
                  >
                    {isApplyingAnswers ? 'Đang chèn...' : 'Chèn vào mô tả'}
                  </button>

                  <button
                    type="button"
                    onClick={handleSendAnswersToAi}
                    disabled={answeredCount === 0 || isSubmittingAnswersToAi}
                    className="flex-1 sm:flex-none px-5 py-2.5 rounded-xl bg-gradient-to-r from-[#c34c36] to-[#dc4729] hover:opacity-95 text-white text-xs font-black flex items-center justify-center gap-2 shadow-sm transition disabled:opacity-40 disabled:cursor-not-allowed cursor-pointer"
                    title="Gửi câu trả lời để AI tổng hợp bài mô tả hoàn chỉnh"
                  >
                    {isSubmittingAnswersToAi ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        <span>AI đang viết mô tả...</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 text-amber-200" />
                        <span>Gửi AI Hoàn Thiện Mô Tả</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Main Editing Fields */}
          <div className="space-y-4">
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-[#24263e]">Tiêu đề bài đăng *</label>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="VD: Tủ Lạnh Panasonic 250L Inverter Tiết Kiệm Điện"
                className="w-full px-4 py-2.5 bg-slate-50 border border-gray-200 rounded-xl text-xs font-bold text-[#24263e] focus:outline-none focus:border-[#c34c36]"
              />
            </div>

            <div className="space-y-1.5">
              <div className="flex items-center justify-between">
                <label className="text-xs font-bold text-[#24263e]">Mô tả chi tiết sản phẩm *</label>
                <span className="text-[10px] text-slate-400">{description.length}/10.000 ký tự</span>
              </div>
              <textarea
                rows={6}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Mô tả chi tiết tình trạng máy móc, thời gian sử dụng, phụ kiện kèm theo..."
                className="w-full px-4 py-3 bg-slate-50 border border-gray-200 rounded-xl text-xs text-slate-800 leading-relaxed focus:outline-none focus:border-[#c34c36]"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-[#24263e]">Tình trạng phân loại (Item Condition)</label>
                <select
                  value={itemCondition}
                  onChange={(e) => setItemCondition(e.target.value)}
                  className="w-full px-3.5 py-2.5 bg-slate-50 border border-gray-200 rounded-xl text-xs font-bold text-[#24263e] focus:outline-none focus:border-[#c34c36]"
                >
                  <option value="NEW">Mới 100% (Nguyên hộp / Chưa qua sử dụng)</option>
                  <option value="LIKE_NEW">Như mới (Grade A+ 99%, hoạt động hoàn hảo)</option>
                  <option value="USED_GOOD">Đã qua sử dụng - Hoạt động tốt (Grade A)</option>
                  <option value="USED_FAIR">Đã qua sử dụng - Có xước nhẹ (Grade B)</option>
                  <option value="USED">Cũ bình thường (Grade C)</option>
                </select>
              </div>
            </div>
          </div>

          {/* Navigation Buttons */}
          <div className="flex justify-between pt-4 border-t border-gray-100">
            <button
              onClick={() => setCurrentStep(1)}
              className="px-5 py-2.5 rounded-xl border border-gray-200 text-slate-700 hover:bg-slate-50 text-xs font-bold flex items-center gap-1.5 cursor-pointer"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Quay lại Bước 1</span>
            </button>

            <button
              onClick={handleGoToStep3}
              disabled={isFinalizingChat}
              className="px-6 py-2.5 rounded-xl bg-[#24263e] hover:bg-black text-white text-xs font-black shadow-xs flex items-center gap-2 transition cursor-pointer disabled:opacity-50"
            >
              {isFinalizingChat ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Đang tổng hợp mô tả...</span>
                </>
              ) : (
                <>
                  <span>Tiếp tục: Xác nhận mô tả</span>
                  <ArrowRight className="w-4 h-4" />
                </>
              )}
            </button>
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* STEP 3: LƯU DRAFT & XÁC NHẬN MÔ TẢ (PUT /draft & POST /accept-description)*/}
      {/* ========================================================================= */}
      {currentStep === 3 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-gray-200 shadow-sm space-y-6">
          <div>
            <h3 className="text-lg font-black text-[#24263e] flex items-center gap-2">
              <CheckCircle2 className="w-5 h-5 text-emerald-600" />
              <span>{lang === 'vi' ? 'Bước 3: Lưu Draft & Xác Nhận Nội Dung Mô Tả' : 'Step 3: Save Draft & Accept Description'}</span>
            </h3>
            <p className="text-xs text-slate-500 mt-1">
              Theo quy chuẩn hệ thống, mô tả phải được xác nhận trước khi bước vào quy trình định giá AI và đăng bài.
            </p>
          </div>

          {/* Summary Card of Description to Accept */}
          <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-3">
            <div className="flex items-center justify-between border-b border-slate-200 pb-2.5">
              <span className="text-xs font-bold text-slate-500 uppercase">Nội dung sẽ được xác nhận:</span>
              <span className={`text-[10px] font-black px-2.5 py-0.5 rounded-full ${descriptionAccepted ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800'}`}>
                {descriptionAccepted ? '✓ Đã xác nhận trước đó' : 'Chờ xác nhận'}
              </span>
            </div>

            <div>
              <span className="text-[11px] font-bold text-slate-500 block">Tiêu đề:</span>
              <h4 className="text-sm font-black text-[#24263e]">{title}</h4>
            </div>

            <div>
              <span className="text-[11px] font-bold text-slate-500 block">Phân loại tình trạng:</span>
              <span className="text-xs font-bold text-slate-800">{itemCondition}</span>
            </div>

            <div>
              <span className="text-[11px] font-bold text-slate-500 block mb-1">Mô tả sản phẩm:</span>
              <div className="p-3 bg-white rounded-xl border border-gray-200 text-xs text-slate-800 whitespace-pre-wrap leading-relaxed">
                {description}
              </div>
            </div>
          </div>

          {/* Responsibility Warning */}
          <div className="p-4 rounded-2xl bg-blue-50 border border-blue-200 text-blue-900 text-xs flex items-start gap-3">
            <Info className="w-5 h-5 text-blue-600 shrink-0 mt-0.5" />
            <div>
              <span className="font-bold block mb-0.5">Quy định thẩm định nội dung:</span>
              <span>Khi bạn xác nhận mô tả, hệ thống sẽ lưu snapshot và khóa dữ liệu để AI tính toán khoảng giá hợp lý. Nếu sau này bạn sửa mô tả, trạng thái sẽ tự động đặt lại và cần xác nhận lại.</span>
            </div>
          </div>

          {/* Navigation Buttons */}
          <div className="flex justify-between pt-4 border-t border-gray-100">
            <button
              onClick={() => setCurrentStep(2)}
              className="px-5 py-2.5 rounded-xl border border-gray-200 text-slate-700 hover:bg-slate-50 text-xs font-bold flex items-center gap-1.5 cursor-pointer"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Sửa lại mô tả</span>
            </button>

            <button
              onClick={handleSaveAndAcceptDescription}
              disabled={isAcceptingDescription}
              className="px-8 py-3 rounded-2xl bg-emerald-600 hover:bg-emerald-700 text-white font-black text-xs shadow-md flex items-center gap-2 transition cursor-pointer disabled:opacity-50"
            >
              {isAcceptingDescription ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Đang lưu và xác nhận mô tả...</span>
                </>
              ) : (
                <>
                  <Check className="w-4 h-4" />
                  <span>Xác Nhận Mô Tả & Tiếp Tục Định Giá AI</span>
                  <ArrowRight className="w-4 h-4" />
                </>
              )}
            </button>
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* STEP 4: ĐỊNH GIÁ AI & CHỌN GIÁ BÁN                                        */}
      {/* ========================================================================= */}
      {currentStep === 4 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-gray-200 shadow-sm space-y-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <h3 className="text-lg font-black text-[#24263e] flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-amber-500" />
                <span>{lang === 'vi' ? 'Bước 4: Định Giá Bằng AI & Chọn Giá Bán' : 'Step 4: AI Valuation & Set Price'}</span>
              </h3>
              <p className="text-xs text-slate-500 mt-1">
                Sử dụng 1 lượt VALUATION để AI phân tích khoảng giá thị trường và đề xuất mức giá thanh khoản tốt nhất.
              </p>
            </div>

            <button
              type="button"
              onClick={handleLoadValuationHistory}
              className="px-3 py-1.5 rounded-xl border border-slate-200 text-slate-700 hover:bg-slate-50 text-xs font-bold flex items-center gap-1.5 cursor-pointer shrink-0"
            >
              <History className="w-3.5 h-3.5" />
              <span>Xem lịch sử định giá</span>
            </button>
          </div>

          {/* Credit VALUATION Box & Trigger Button */}
          <div className="p-5 rounded-2xl bg-gradient-to-r from-slate-900 to-[#24263e] text-white flex flex-col sm:flex-row sm:items-center justify-between gap-4 shadow-md">
            <div>
              <span className="text-[11px] font-bold text-slate-400 block uppercase tracking-wider">Tín dụng Định Giá AI</span>
              <div className="text-base font-black flex items-center gap-2 mt-0.5">
                <span>Bạn đang có:</span>
                <span className="px-2.5 py-0.5 rounded-lg bg-amber-400 text-slate-950 font-mono font-black text-sm">
                  {credits?.valuation ?? 0} VALUATION
                </span>
              </div>
              <span className="text-[11px] text-slate-300 block mt-1">
                * Mỗi lần định giá thành công trừ 1 VALUATION. Retry do lỗi mạng không bị trừ lại.
              </span>
            </div>

            <div className="flex items-center gap-2 shrink-0">
              <button
                type="button"
                onClick={handleRunAiValuation}
                disabled={isEstimatingPrice || (credits?.valuation ?? 0) < 1}
                className="px-5 py-3 rounded-xl bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-300 hover:to-amber-400 text-slate-950 font-black text-xs shadow-md flex items-center gap-2 transition cursor-pointer disabled:opacity-50"
              >
                {isEstimatingPrice ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    <span>AI đang phân tích thị trường...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4" />
                    <span>Định Giá Bằng AI (1 Credit)</span>
                  </>
                )}
              </button>
            </div>
          </div>

          {/* AI Valuation Result Card */}
          {valuationResult && (
            <div className="p-5 rounded-2xl bg-emerald-50 border border-emerald-200 space-y-4 animate-fadeIn">
              <div className="flex items-center justify-between">
                <span className="text-xs font-black text-emerald-900 flex items-center gap-1.5 uppercase">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                  Kết quả định giá thành công từ mô hình {valuationResult.modelVersion || 'AI'}
                </span>
                <span className="text-[11px] text-emerald-700 font-bold font-mono">
                  Mã Y/c: {valuationRequestId ? valuationRequestId.slice(0, 8) : 'Live'}
                </span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div className="p-3.5 bg-white rounded-xl border border-emerald-100 shadow-xs">
                  <span className="text-[11px] text-slate-500 font-bold block">Khoảng giá hợp lý:</span>
                  <div className="text-sm font-black text-slate-800 mt-1">
                    {formatVND(valuationResult.fairPriceMin)} - {formatVND(valuationResult.fairPriceMax)}
                  </div>
                </div>

                <div className="p-3.5 bg-white rounded-xl border border-emerald-300 shadow-xs ring-2 ring-emerald-500/20">
                  <span className="text-[11px] text-emerald-700 font-bold block">Giá đề xuất bán tốt nhất:</span>
                  <div className="text-base font-black text-[#c34c36] mt-1">
                    {formatVND(valuationResult.suggestedPrice)}
                  </div>
                </div>

              
              </div>

              <div className="flex justify-end">
                <button
                  type="button"
                  onClick={() => setFinalPriceVnd(valuationResult.suggestedPrice)}
                  className="px-4 py-2 bg-emerald-700 hover:bg-emerald-800 text-white rounded-xl text-xs font-bold transition cursor-pointer flex items-center gap-1.5"
                >
                  <Check className="w-3.5 h-3.5" />
                  <span>Áp dụng giá AI đề xuất ({formatVND(valuationResult.suggestedPrice)})</span>
                </button>
              </div>
            </div>
          )}

          {/* History Modal / Drawer */}
          {showValuationHistory && (
            <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-[#24263e]">Lịch sử các lần định giá cho bài đăng này:</span>
                <button
                  onClick={() => setShowValuationHistory(false)}
                  className="text-xs text-slate-400 hover:text-slate-600"
                >
                  ✕ Đóng
                </button>
              </div>
              {valuationHistory.length > 0 ? (
                <div className="space-y-2">
                  {valuationHistory.map((h, i) => (
                    <div key={i} className="p-2.5 bg-white rounded-xl border border-gray-200 text-xs flex items-center justify-between">
                      <div>
                        <span className="font-bold text-slate-800">{formatVND(h.suggestedPrice)}</span>
                        <span className="text-[10px] text-slate-400 ml-2">Khoảng: {formatVND(h.fairPriceMin)} - {formatVND(h.fairPriceMax)}</span>
                      </div>
                      <span className="text-[10px] text-slate-500">{h.createdAt ? new Date(h.createdAt).toLocaleDateString() : 'Vừa xong'}</span>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-slate-400 italic">Chưa có lịch sử định giá trước đó.</p>
              )}
            </div>
          )}

          {/* Price Input Form */}
          <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
              <label className="text-xs font-bold text-[#24263e] uppercase">
                Giá bán của bạn (VND) *
              </label>
              <span className="text-lg font-black text-[#c34c36]">
                {formatVND(finalPriceVnd)}
              </span>
            </div>

            <div className="relative">
              <DollarSign className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
              <input
                type="number"
                value={finalPriceVnd}
                onChange={(e) => setFinalPriceVnd(Number(e.target.value))}
                step={50000}
                min={1000}
                className="w-full pl-9 pr-4 py-3 bg-white border border-gray-200 rounded-xl text-sm font-black text-slate-900 focus:outline-none focus:border-[#c34c36]"
              />
            </div>

            {/* High-value threshold notice (> 5,000,000 VND) */}
            {finalPriceVnd > 5000000 && (
              <div className="p-3.5 rounded-xl bg-cyan-50 border border-cyan-200 text-cyan-900 text-xs flex items-start gap-2.5">
                <ShieldCheck className="w-4 h-4 text-cyan-700 shrink-0 mt-0.5" />
                <div>
                  <span className="font-bold block">Sản phẩm giá trị cao (trên 5.000.000 VND):</span>
                  <span>Bài đăng sẽ tự động chuyển sang quy trình Kiểm định chất lượng của Kỹ thuật viên (PENDING_INSPECTION) trước khi hiển thị công khai trên Sàn. Chưa trừ credit LISTING cho tới khi kiểm định đạt chuẩn.</span>
                </div>
              </div>
            )}
          </div>

          {/* Navigation Buttons */}
          <div className="flex justify-between pt-4 border-t border-gray-100">
            <button
              onClick={() => setCurrentStep(3)}
              className="px-5 py-2.5 rounded-xl border border-gray-200 text-slate-700 hover:bg-slate-50 text-xs font-bold flex items-center gap-1.5 cursor-pointer"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Quay lại Xác nhận mô tả</span>
            </button>

            <button
              onClick={() => setCurrentStep(5)}
              disabled={!finalPriceVnd || finalPriceVnd < 1000}
              className="px-6 py-2.5 rounded-xl bg-[#24263e] hover:bg-black text-white text-xs font-black shadow-xs flex items-center gap-2 transition cursor-pointer disabled:opacity-50"
            >
              <span>Tiếp tục: Xem lại & Gửi đăng</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* ========================================================================= */}
      {/* STEP 5: XEM LẠI & GỬI ĐĂNG BÀI (POST /api/v1/posts/submit/{postId})       */}
      {/* ========================================================================= */}
      {currentStep === 5 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-gray-200 shadow-sm space-y-6">
          <div>
            <h3 className="text-lg font-black text-[#24263e] flex items-center gap-2">
              <ShieldCheck className="w-5 h-5 text-[#c34c36]" />
              <span>{lang === 'vi' ? 'Bước 5: Xem Lại Thông Tin & Gửi Đăng Bài' : 'Step 5: Review & Submit Listing'}</span>
            </h3>
            <p className="text-xs text-slate-500 mt-1">
              Kiểm tra toàn bộ thông tin lần cuối trước khi nộp duyệt bài đăng lên hệ thống SecondLife.
            </p>
          </div>

          {/* Final Summary Card */}
          <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-200 pb-3">
              <div>
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Tiêu đề bài đăng</span>
                <h4 className="text-base font-black text-[#24263e]">{title}</h4>
              </div>
              <div className="text-right">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">Giá niêm yết</span>
                <span className="text-xl font-black text-[#c34c36]">{formatVND(finalPriceVnd)}</span>
              </div>
            </div>

            {/* Photos Preview */}
            <div>
              <span className="text-xs font-bold text-slate-600 block mb-2">Bộ ảnh sản phẩm đã tải:</span>
              <div className="flex flex-wrap gap-2">
                {photoPreviews.map((p, i) => (
                  <img key={i} src={p} alt="" className="w-16 h-16 rounded-xl object-cover border border-gray-200 shadow-xs" />
                ))}
              </div>
            </div>

            {/* Description Preview */}
            <div>
              <span className="text-xs font-bold text-slate-600 block mb-1">Mô tả sản phẩm:</span>
              <div className="p-3.5 bg-white rounded-xl border border-gray-200 text-xs text-slate-800 whitespace-pre-wrap leading-relaxed max-h-40 overflow-y-auto">
                {description}
              </div>
            </div>

            {/* Credit Notice */}
            <div className="p-3.5 rounded-xl bg-amber-50 border border-amber-200 text-xs text-amber-900 flex items-center justify-between">
              <span>Credit LISTING cần dùng: <strong>1 lượt</strong> (Chỉ trừ khi bài đăng chính thức chuyển sang <strong>ACTIVE</strong>).</span>
              <span className="font-bold">Số dư hiện tại: {credits?.listing ?? 0} lượt</span>
            </div>
          </div>

          {/* Submission Result Banner */}
          {submitResult && (
            <div
              className={`p-5 rounded-2xl border space-y-4 animate-fadeIn ${submitResult.status === 'ACTIVE'
                ? 'bg-emerald-50 border-emerald-300 text-emerald-950'
                : submitResult.status === 'INSUFFICIENT_CREDIT'
                  ? 'bg-amber-50 border-amber-300 text-amber-950'
                  : submitResult.status === 'PENDING_INSPECTION'
                    ? 'bg-cyan-50 border-cyan-300 text-cyan-950'
                    : submitResult.status === 'PENDING'
                      ? 'bg-amber-50 border-amber-300 text-amber-950'
                      : 'bg-rose-50 border-rose-300 text-rose-950'
                }`}
            >
              <div className="flex items-start gap-3">
                {submitResult.status === 'ACTIVE' ? (
                  <CheckCircle2 className="w-6 h-6 text-emerald-600 shrink-0 mt-0.5" />
                ) : submitResult.status === 'INSUFFICIENT_CREDIT' ? (
                  <AlertTriangle className="w-6 h-6 text-amber-600 shrink-0 mt-0.5" />
                ) : submitResult.status === 'PENDING_INSPECTION' ? (
                  <ShieldCheck className="w-6 h-6 text-cyan-600 shrink-0 mt-0.5" />
                ) : submitResult.status === 'PENDING' ? (
                  <AlertTriangle className="w-6 h-6 text-amber-600 shrink-0 mt-0.5" />
                ) : (
                  <AlertTriangle className="w-6 h-6 text-rose-600 shrink-0 mt-0.5" />
                )}
                <div className="space-y-1">
                  <h4 className="font-black text-sm uppercase">
                    {submitResult.status === 'ACTIVE'
                      ? 'Đăng bài thành công! (ACTIVE)'
                      : submitResult.status === 'INSUFFICIENT_CREDIT'
                        ? 'Cần nạp thêm Credit để thanh toán phí kiểm định'
                        : submitResult.status === 'PENDING_INSPECTION'
                          ? 'Chờ kiểm định chất lượng trung tâm (PENDING_INSPECTION)'
                          : submitResult.status === 'PENDING'
                            ? 'Nghi ngờ trùng lặp - Chờ STAFF kiểm duyệt (PENDING)'
                            : 'Bài đăng bị từ chối (REJECTED)'}
                  </h4>
                  <p className="text-xs leading-relaxed">
                    {submitResult.message || (
                      submitResult.status === 'ACTIVE'
                        ? 'Bài đăng của bạn đã được xuất bản công khai. Đã trừ 1 lượt LISTING.'
                        : submitResult.status === 'INSUFFICIENT_CREDIT'
                          ? 'Sản phẩm có giá trị > 5.000.000 đ bắt buộc phải qua kiểm định. Bạn chưa có đủ credit để thanh toán phí.'
                          : submitResult.status === 'PENDING_INSPECTION'
                            ? 'Sản phẩm có giá trị > 5 triệu đồng đang chờ Kỹ thuật viên trung tâm kiểm định tiếp nhận.'
                            : submitResult.status === 'PENDING'
                              ? 'Phát hiện hình ảnh hoặc nội dung trùng với bài đăng khác trên sàn. Nhân viên Staff sẽ đối soát thủ công.'
                              : (submitResult.reviewReason || 'Bài đăng không đạt tiêu chuẩn nội dung của sàn. Không trừ credit.')
                    )}
                  </p>
                </div>
              </div>

              {/* Fee Breakdown if Inspection is required */}
              {submitResult.inspectionRequired && (
                <div className="p-3.5 bg-white/90 rounded-xl border border-slate-200 grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs">
                  <div>
                    <span className="text-slate-500 block text-[11px]">Phí kiểm định kỹ thuật:</span>
                    <span className="font-black text-slate-800">
                      {formatVND(Number(submitResult.inspectionFee || 200000))}
                    </span>
                  </div>
                  <div>
                    <span className="text-slate-500 block text-[11px]">Phí vận chuyển trung tâm:</span>
                    <span className="font-black text-slate-800">
                      {formatVND(Number(submitResult.shippingFee || 50000))}
                    </span>
                  </div>
                  {submitResult.creditShortfall != null && Number(submitResult.creditShortfall) > 0 && (
                    <div className="col-span-2 sm:col-span-1">
                      <span className="text-rose-600 block text-[11px] font-bold">Số tiền/credit còn thiếu:</span>
                      <span className="font-black text-rose-600 text-sm">
                        {formatVND(Number(submitResult.creditShortfall))}
                      </span>
                    </div>
                  )}
                </div>
              )}

              {submitResult.duplicateMatches && submitResult.duplicateMatches.length > 0 && (
                <div className="p-3 bg-white/80 rounded-xl text-xs space-y-1">
                  <span className="font-bold text-slate-700 block">Danh sách bài đối chiếu trùng khớp:</span>
                  <div className="font-mono text-[11px] text-slate-600">
                    {submitResult.duplicateMatches.join(', ')}
                  </div>
                </div>
              )}

              <div className="flex flex-wrap items-center justify-end gap-2 pt-1">
                {submitResult.status === 'INSUFFICIENT_CREDIT' ? (
                  <>
                    <button
                      type="button"
                      onClick={handleQuickBuyCredit}
                      disabled={isPurchasingCredits}
                      className="px-4 py-2 rounded-xl bg-[#c34c36] hover:bg-[#a83c28] text-white text-xs font-bold transition flex items-center gap-1.5 shadow-xs cursor-pointer"
                    >
                      {isPurchasingCredits ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Plus className="w-3.5 h-3.5 text-amber-300" />}
                      <span>Nạp thêm Credit ngay</span>
                    </button>
                    <button
                      type="button"
                      onClick={handleSubmitPostFinal}
                      disabled={isSubmittingPost}
                      className="px-4 py-2 rounded-xl bg-[#24263e] hover:bg-black text-white text-xs font-bold transition cursor-pointer"
                    >
                      Thử gửi lại bài đăng
                    </button>
                  </>
                ) : (
                  <>
                    {submitResult.status === 'REJECTED' && (
                      <button
                        type="button"
                        onClick={() => {
                          setSubmitResult(null);
                          setCurrentStep(3);
                        }}
                        className="px-4 py-1.5 rounded-xl bg-[#c34c36] hover:bg-[#a83c28] text-white text-xs font-bold transition flex items-center gap-1.5 shadow-xs cursor-pointer"
                      >
                        <ArrowLeft className="w-3.5 h-3.5" />
                        <span>Sửa lại thông tin</span>
                      </button>
                    )}
                    <button
                      type="button"
                      onClick={loadCredits}
                      className="px-3.5 py-1.5 rounded-xl bg-white border border-gray-200 text-xs font-bold text-slate-700 hover:bg-slate-50 transition cursor-pointer"
                    >
                      Kiểm tra lại số dư credit
                    </button>
                    <button
                      type="button"
                      onClick={handleFinishAndExit}
                      className="px-4 py-1.5 rounded-xl bg-[#24263e] hover:bg-black text-white text-xs font-bold transition cursor-pointer"
                    >
                      Hoàn tất & Về Bàn làm việc
                    </button>
                  </>
                )}
              </div>
            </div>
          )}

          {submitError && (
            <div className="p-4 rounded-2xl bg-rose-50 border border-rose-200 text-rose-800 text-xs flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-rose-600 shrink-0" />
              <span>{submitError}</span>
            </div>
          )}

          {/* Navigation & Submit Button */}
          {!submitResult && (
            <div className="flex justify-between pt-4 border-t border-gray-100">
              <button
                onClick={() => setCurrentStep(4)}
                className="px-5 py-2.5 rounded-xl border border-gray-200 text-slate-700 hover:bg-slate-50 text-xs font-bold flex items-center gap-1.5 cursor-pointer"
              >
                <ArrowLeft className="w-4 h-4" />
                <span>Quay lại Định giá</span>
              </button>

              <button
                onClick={handleSubmitPostFinal}
                disabled={isSubmittingPost || (credits?.listing ?? 0) < 1}
                className="px-8 py-3.5 rounded-2xl bg-gradient-to-r from-[#c34c36] to-[#24263e] hover:opacity-95 text-white font-black text-sm shadow-md flex items-center gap-2 transition cursor-pointer disabled:opacity-50"
              >
                {isSubmittingPost ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    <span>Đang gửi bài lên Backend...</span>
                  </>
                ) : (
                  <>
                    <ShieldCheck className="w-5 h-5 text-amber-300" />
                    <span>Gửi Đăng Bài Ngay (Trừ 1 LISTING khi ACTIVE)</span>
                  </>
                )}
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
};